name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fenggp
          password: 13590052778Docker
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64/v8
          push: true
          tags: fenggp/server-app:latest