name: Build Docker Container

on:
  push:
    branches:
      - main
      - master 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: fenggp
          password: 13590052778Docker
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: fenggp/server-app:latest